#
# .travis.yml
# mas-cli
#
# https://travis-ci.com/mas-cli/mas
# https://docs.travis-ci.com/user/reference/osx/
# https://docs.travis-ci.com/user/languages/objective-c/
#

os: osx
osx_image: xcode10         # macOS 10.13

git:
  depth: 1
  submodules: false

env:
  global:
  - LANG=en_US.UTF-8
  - LC_ALL=en_US.UTF-8
  - LANGUAGE=en_US.UTF-8
  - HOMEBREW_NO_AUTO_UPDATE=1
  - HOMEBREW_BINTRAY_USER=phatblat
  - TAP_BOTTLE_DOMAIN=https://dl.bintray.com/phatblat
  - AWS_REGION=us-west-2 # needed because the aws-sdk-s3 gem errors without it
  - S3_BUCKET=homebrew-mas-travis
  # Beyond these global variables, you also need to set some secret variables
  # in your travis-ci settings:
  # - AWS_ACCESS_KEY_ID
  # - AWS_SECRET_ACCESS_KEY          (for the AWS S3 bucket)
  # - GITHUB_TOKEN                   (for pushing bottle DSL commits)
  # - HOMEBREW_BINTRAY_KEY           (for the Bintray repo)
  # - DANGER_GITHUB_API_TOKEN        (for running Danger gem)

install:
- script/bootstrap

stages:
- Assemble
- Deploy

jobs:
  include:
  # Assemble stage
  - stage: Assemble

    script:
    - script/build
    - script/archive
    - script/package
    - bundle exec danger

    after_success:
    - bundle exec script/travis_upload.rb $S3_BUCKET $TRAVIS_BUILD_NUMBER

  # Deploy stage
  - stage: Deploy
    script:
    - |
      if test -n "$TRAVIS_TAG"; then
        echo "🚀 Deploying from tag $TRAVIS_TAG"
      else
        if test -n "$TRAVIS_PULL_REQUEST"; then
          echo "🛑 Skipping deployment as build is from a PR -> $TRAVIS_PULL_REQUEST_SLUG/$TRAVIS_PULL_REQUEST_BRANCH -> $TRAVIS_BRANCH"
        else
          echo "🛑 Skipping deployment as build is from branch -> $TRAVIS_BRANCH"
        fi
      fi

    before_deploy:
    - bundle exec script/travis_download.rb $S3_BUCKET $TRAVIS_BUILD_NUMBER

    # GitHub Releases
    deploy:
      provider: releases
      api_key:
        # "automatic releases for mas-cli/mas" personal access token on @phatblat with scopes:
        # - public_repo
        secure: HMlaLttliCMwJRbJvo2Ddme1OKekPWfxN99SWRjnVTDzJPlLiqWd1KyvEJPHBxlMv5pZ2LnDE9U2iFrB9W/UR9DJ+JHFiyuBdIr9V6RuvFpObGDXQ+v4LMc5q+kt+2rpq3U4kAcbR0QgZR0hc/jrGCjRWRRNEEm1APrh0MnbeN17aaUX+go+zNAvA/+m8fUHe2XwMd3HBg0vtHMB/tJGhAZC26bXGsT5wYaY1oEWUbAlBFB+hHCaCGjOOUySoElrTRGocO3D4U6LpNlSSQrEYTrvMxjPFrwDAfdzxVyoMP4Au1Sv8sYs2DCNdZnOVPW9s4KHYcDMjdDHcSPg2c63NgxyYkzaYncIjhruAL1IKb3COYiz6G0ldrLuAsp62VX8+Ul72ykiM54H5yp7ESJhHVipqTJs+7l6ChCkErW8PNsBTWXufwO+N9Qs1F4ZsdA0m9+1lqqAoc+8zSDnTchSimujLEQsNAlC590Oka7EK0rtCgFJfvPlEfLazd/weXsN9wohsnw78O/+qrwJaPJgYM9sxhLJMRGXUCzknEFIs292vDSObfGbPF81I9OhuI3Vy9jXvApnSVhGXR2VGfjBBK6lGY0q6xbvnadirRzu3e/qo6GEXNQI/S2gJoZDsU6plXXoPi4dL+ZV/X/+w/ePUSfBc4WBgW6lJogvdWqiTzo=
      file_glob: true
      file:
      - build/*.zip
      - *.pkg
      skip_cleanup: true
      on:
        repo: mas-cli/mas
        tags: true
      # TODO: add name, body content to release https://docs.travis-ci.com/user/deployment/releases/#advanced-options

    after_deploy:
    - script/formulate
    - script/bottle
