#
# .github/workflows/build-test.yml
#
# https://docs.github.com/en/actions/reference/environment-variables#default-environment-variables

name: Build, Test, and Lint

on: [push]

jobs:
  build-test:

    # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
    name: Build, Test, and Lint
    # https://docs.github.com/en/actions/hosting-your-own-runners/using-self-hosted-runners-in-a-workflow
    # https://github.com/mas-cli/mas/settings/actions/runners
    runs-on: [self-hosted, macOS]
    steps:

      # https://github.com/actions/checkout#usage
    - uses: actions/checkout@master
      with:
        # Fetch tags for script/version
        fetch-depth: 0
        # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Bootstrap
      run: script/bootstrap
      # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsenv

    - name: Build
      run: script/build

    - name: Test
      run: script/test

    - name: Lint
      run: script/lint
